
import './styles.css'
import 'bootstrap/dist/css/bootstrap.css';
import { Header } from './components/Header';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Sharetrade',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Slab:wght@700&display=swap" />
      </head>
      <body>
        <Header />
          {children}
      </body>
    </html>
  )
}
